In [1]:
import numpy as np

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
1 + np.arange(10)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a1 = np.arange(3, 9)
a1

array([3, 4, 5, 6, 7, 8])

In [4]:
a3 = np.arange(3, 9, 2)
a3

array([3, 5, 7])

In [6]:
a = [0, 1, 2, 3]
array = np.array(a)
print(array)

[0 1 2 3]


In [10]:
x = np.array([1.0, 2.0, 3.0])
x
y = np.array([2.0, 4.0, 6.0])
y
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [13]:
A = np.array([1.0, 2.0, 3.0])
print(A.shape)
print(A.dtype)
print(A / 2.0)

(3,)
float64
[0.5 1.  1.5]


In [21]:
A = np.array([[1,2], [3,4]])
print(A)
#print(A.shape)
#print(A.dtype)
B = np.array([[3, 0], [0, 6]])
print(B)
print(A+B)
print(A*B)

[[1 2]
 [3 4]]
[[3 0]
 [0 6]]
[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]


In [33]:
a1 = np.zeros((3, 3))
print(a1)
print(a1.shape)
a2 = np.ones((2, 2), dtype=str)
print(a2)
print(a2.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
[['1' '1']
 ['1' '1']]
(2, 2)


In [43]:
# 원소 접근
A = np.array([[1, 2], [3, 4]])
print(A)
print(A[0])
print(A[1])
print(A[1][1])

for row in A:
    print(row)

# 브로드 캐스트 - 형상이 다른 배열끼리 연산 수행
B = np.array([10, 20])
print(B[0])
print(B[1])
print(A+B)
print(A*B)

[[1 2]
 [3 4]]
[1 2]
[3 4]
4
[1 2]
[3 4]
10
20
[[11 22]
 [13 24]]
[[10 40]
 [30 80]]


### 2019년 프로야구 성적표

In [63]:
import numpy as np

순위 = 1 + np.arange(10)
팀 = np.array(['SSG', 'LG', '키움', 'LG', 'KT', '기아', 'NC', '삼성', '롯데', '두산', '한화'])
승 = np.array([88, 87, 80, 80, 70, 67, 66, 64, 60, 46])
패 = np.array([52, 55, 62, 62, 73, 74, 76, 76, 82, 96])
무 = np.array([4, 2, 2, 2, 1, 3, 2, 4, 2, 2])
승률 = np.array([0.629, 0.613, 0.563, 0.563, 0.490, 0.475, 0.465, 0.457, 0.423, 0.324])

with open("data/2019kbo.txt", 'w') as f:
    f.write("========== 2022 한국 프로야구 성적표 ==========\n")
    head = "순위\t팀\t승\t패\t무\t승률"
    f.write(head)
    f.write('\n')
    for i in range(len(team)):
        txt = f'{순위[i]}\t{팀[i]}\t{승[i]}\t{패[i]}\t{무[i]}\t{승률[i]}\n'
        f.write(txt)

In [64]:
with open("data/2019kbo.txt", 'r') as f:
    data = f.read()
    print(data)

========== 2022 한국 프로야구 성적표 ==========
순위	팀	승	패	무	승률
1	SSG	88	52	4	0.629
2	LG	87	55	2	0.613
3	키움	80	62	2	0.563
4	LG	80	62	2	0.563
5	KT	70	73	1	0.49
6	기아	67	74	3	0.475
7	NC	66	76	2	0.465
8	삼성	64	76	4	0.457
9	롯데	60	82	2	0.423
10	두산	46	96	2	0.324

